# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsearch(self):
    self.driver.get("https://ceshiren.com/")
    self.driver.set_window_size(1512, 882)

    element = self.driver.find_element(By.ID, "search-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element()
    self.driver.find_element(By.CSS_SELECTOR, ".d-icon-search").click()
    self.driver.find_element(By.ID, "search-term").click()
    self.driver.find_element(By.ID, "search-term").send_keys("selenium")
    self.driver.find_element(By.CSS_SELECTOR, ".d-icon-sliders-h").click()
    self.driver.find_element(By.ID, "search-term").text
  
